flow configuration examples
banzaicloud/one-eye-docs pull request #1
Opened 2020-04-15 10:44 UTC by bshifter

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | Apache 2.0

### What's in this PR?
logging flow configuration examples

### To Do
replace labels with the new logging-extensions image

2020-04-15 13:10 UTC, pepov requested changes

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +### Example: Configure logging Flow to listen Eventtailer
```suggestion
### Example: Configure logging Flow to route logs from an event tailer
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +  - stdout: {}
```suggestion
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +    - null-output
```suggestion
    - sample-output
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +        app.kubernetes.io/name: sample-event-tailer
```suggestion
        app.kubernetes.io/name: sample-eventtailer
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +The following example uses the flow's match term to listen the previously created "sample" Eventtailer's log.
```suggestion
The following example configures a flow to route the previously created `sample-eventtailer` EventTailer's log. 
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +The following example uses the flow's match term to listen the previously created "sample" Hosttailer's log.
```suggestion
The following example uses the flow's match term to route the previously created "sample" HostTailer's log. 
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +  - stdout: {}
```suggestion
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +    - null-output
```suggestion
    - sample-output
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +### Example: Configure logging Flow to listen Hosttailer
```suggestion
### Example: Configure logging Flow to route host logs
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +        app.kubernetes.io/name: sample-tailer
```suggestion
        app.kubernetes.io/name: sample
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +        - sample-tailer-nginx-access
```suggestion
        - nginx-access
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +### Example: configuration Kubernetes host tailer with multiple tailers
```suggestion
### Example: configure multiple host tailers
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +  enableRecreateWorkloadOnImmutableFieldChange: true
```suggestion
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +      disabled: true
```suggestion
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +      disabled: false
```suggestion
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +      disabled: false
```suggestion
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +| containerOverrides | *types.ContainerBase | No | - | Override container fields for the given daemonset<br> |
```suggestion
```

2020-04-15 13:10 UTC, pepov commented on docs/logging-extensions/_index.md
> +### Example: Configure logging Flow with explicit exclusion
we don't need this example, log routing is discussed in detail in the logging-operator docs

2020-04-15 13:59 UTC, bshifter commented on docs/logging-extensions/_index.md
> +        app.kubernetes.io/name: sample-event-tailer
// EventTailer configuration
var EventTailer = EventTailerConfig{
	TailerAffix:           "event-tailer",
	ConfigurationFileName: "config.json",
	PositionVolumeName:    "event-tailer-position",
}

2020-04-15 14:01 UTC, bshifter commented on docs/logging-extensions/_index.md
> +        app.kubernetes.io/name: sample-event-tailer
the label name will be "sample-event-tailer" with the current configuration

2020-04-16 10:59 UTC, pepov approved these changes

2020-04-16 11:02 UTC, merged