Thanos multicluster metrics mvp docs
banzaicloud/one-eye-docs pull request #43
Opened 2021-04-16 13:13 UTC by fekete-robert

.

2021-04-20 06:00 UTC, tarokkk requested changes

2021-04-20 06:00 UTC, tarokkk commented on docs/quickstart/multicluster.md
> +        name: selfsigned
```suggestion
            name: selfsigned
```

2021-04-20 06:02 UTC, tarokkk commented on docs/quickstart/multicluster.md
> +        kubectl neat get secret peer-tls -o yaml > peer-tls.yaml
```suggestion
        kubectl get secret peer-tls -o yaml > peer-tls.yaml
```

2021-04-21 07:17 UTC, pepov commented on docs/headless/warning-prometheus-label.md
> +If One Eye has been installed on the peer cluster, make sure that the name of the observer custom resource is different on the observer and the peer clusters.
```suggestion
If One Eye has been installed on the peer cluster, make sure that the `spec.clusterName` field of the observer custom resource is different on the observer and the peer clusters. Latest version of `One Eye` (>=0.5.0) tries to detect it automatically from the context.
```

2021-04-21 07:17 UTC, pepov commented on docs/quickstart/multicluster.md
> +- You have completed the steps described in {{% xref "/docs/one-eye/quickstart/_index.md" %}} and you have a working One Eye deployment.
we don't need the full quickstart here as the steps describe the full setup process.

2021-04-21 07:17 UTC, pepov commented on docs/quickstart/multicluster.md
> +            monitoring.banzaicloud.io/thanospeer-ca: ${PEER_ENDPOINT}
we should highlight the fact that these labels are important for the thanospeer to be able to use them automatically

2021-04-21 07:17 UTC, pepov commented on docs/whatsnew/_index.md
> +
we should also add external ingress + authentication with pomerium + role based authorization as a note here, although we don't have the docs for it just yet

2021-04-23 13:52 UTC, tarokkk approved these changes
Nice job thanks

2021-04-23 13:52 UTC, merged